//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsurenceCar.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Car
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public double Horsepower { get; set; }
        public string VIN { get; set; }
        public int DriverId { get; set; }
        public string Passport { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public int ModelsId { get; set; }

        public string CarData
        {
            get
            {
                return Model.Name.ToString() + " " + Number;
            }
        }

        [JsonIgnore]
        public Driver Driver
        {
            get
            {
                return DBConnection.Drivers.FirstOrDefault(Driver => Driver.Id == DriverId);
            }
            set
            {
                DriverId = value.Id;
            }
        }

        [JsonIgnore]
        public Model Model {
            get
            {
                return DBConnection.Models.FirstOrDefault(x => x.Id == ModelsId);
            }
            set
            {
                ModelsId = value.Id;
            }
        }

        public virtual ICollection<Casco> Casco { get; set; }
        public virtual ICollection<EmergencyApplication> EmergencyApplication { get; set; }
        public virtual ICollection<Osago> Osago { get; set; }
    }
}
