//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsurenceCar.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class EmergencyApplication
    {

        public int Id { get; set; }
        public int DriverId { get; set; }
        public int CarId { get; set; }
        public System.DateTime DateEmergency { get; set; }
        public int StatusId { get; set; }
        public double Price { get; set; }
        public int ApplicationType { get; set; }

        [JsonIgnore]
        public Car Car
        {
            get
            {
                return DBConnection.Cars.FirstOrDefault(c => c.Id == Id); 
            }
            set
            {
                CarId = value.Id;
            }
        }

        [JsonIgnore]
        public Driver Driver
        {
            get
            {
                return DBConnection.Drivers.FirstOrDefault(Driver => Driver.Id == Id);
            }
            set
            {
                DriverId = value.Id;
            }
        }

        [JsonIgnore]
        public Status Status
        {
            get
            {
                return DBConnection.Statuses.FirstOrDefault(x => x.Id == Id);
            }
            set
            {
                StatusId = value.Id;
            }
        }

        public virtual ICollection<PhotoEmergency> PhotoEmergency { get; set; }
    }
}