//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsurenceCar.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Osago
    {
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int RegionId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int CarId { get; set; }
        public double Price { get; set; }

        [JsonIgnore]
        public Car Car
        {
            get
            { 
                return DBConnection.Cars.FirstOrDefault(x => x.Id == Id);
            }
            set
            {
                CarId = value.Id;
            }

        }
        [JsonIgnore]
        public Driver Driver {
            get
            {
                return DBConnection.Drivers.FirstOrDefault(x => x.Id == Id);
            }
            set
            {
                DriverId = value.Id;
            }
        }
        [JsonIgnore]
        public Region Region {
            get
            {
                return DBConnection.Regions.FirstOrDefault(x => x.Id == Id);
            }
            set
            {
                RegionId = value.Id;
            }
        }
    }
}
