//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsurenceCar.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class PhotoEmergency
    {
        public int Id { get; set; }
        public int EmergencyApplicationId { get; set; }
        public byte[] Photo { get; set; }

        [JsonIgnore]
        public EmergencyApplication EmergencyApplication
        {
            get
            {
                return DBConnection.EmergencyApplications.FirstOrDefault(x => x.Id == Id);
            }
            set
            {
                EmergencyApplicationId = value.Id;
            }
        }
    }
}
