//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsurenceCar.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Staff
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surename { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }

        [JsonIgnore]
        public User User
        {
            get
            {
                return DBConnection.Users.FirstOrDefault(u => u.Id == Id);
            }
            set
            {
                UserId = value.Id;
            }
        }
    }
}
